name: Meu Primeiro Workflow de CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md

jobs:
  meu-primeiro-job:
    runs-on: ubuntu-latest
    steps:
      - name: Exibir RA e Nome
        run: echo "RA6324630 - Ryan Afonso Lopes de Oliveira"
      
      - name: Mostra o diretório de trabalho
        run: pwd

      - name: Imprime o nome do repositório
        run: echo "Nome do repositório: ${{ github.repository }}